menu_text = '''
        MENU               
 [1] rock, paper, scissors. 
 [2] dino game.            
 [3] quick draw.           
 [Q] Press Q to Quit       
'''
CAM_ERROR = 'Camera not found.'
ERROR_MESSAGE = 'An error occurred. Please try again later.'
FAIL = 'Failure. Please try again'
GREETING = 'Hello, welcome to our program!'
PAPER = 'paper'
PLAYER = 'Player '
PLAYER1 = 'Player 1'
PLAYER1_WIN = 'Player 1 wins.'
PLAYER2 = 'Player 2'
PLAYER2_WIN = 'Player 2 wins.'
ROCK = 'rock'
SCISSORS = 'scissors'
TIED = 'Tie'
process = 'Processing!'
start = 'Start'
time = 'Enter/Back time: '
press = 'PRESS UP!'
drawing = 'You are drawing '
game_time = 'Game time: '
tutor_to_exit = 'Hold your hand horizontally to return to the menu'
waiting_to_exit = 'Please hold still'
warn_one_hand = 'Please use only one hand for selection'
window_name = 'Hand Gestures - Games'
